# Generated by Django 6.0.2 on 2026-03-09 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_setup", "0002_sitesetup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesetup",
            options={"verbose_name": "Setup", "verbose_name_plural": "Setup"},
        ),
    ]
