"""
This type stub file was generated by pyright.
"""

from django.contrib import admin
from django.contrib.admin.options import InlineModelAdmin
from django_summernote.forms import AttachmentAdminForm
from django_summernote.utils import get_config

class SummernoteModelAdminMixin:
    summernote_fields = ...
    def formfield_for_dbfield(self, db_field, *args, **kwargs):
        ...
    


class SummernoteInlineModelAdmin(SummernoteModelAdminMixin, InlineModelAdmin):
    ...


class SummernoteModelAdmin(SummernoteModelAdminMixin, admin.ModelAdmin):
    ...


class AttachmentAdmin(admin.ModelAdmin):
    list_display = ...
    search_fields = ...
    ordering = ...
    form = AttachmentAdminForm


if not get_config()['disable_attachment']:
    ...
