"""
This type stub file was generated by pyright.
"""

from django import forms

FIELD = ...
class UploadForm(forms.Form):
    file = ...


class AttachmentAdminForm(forms.ModelForm):
    file = ...
    class Meta:
        model = ...
        fields = ...
    
    


