"""
This type stub file was generated by pyright.
"""

from django.db import models

__all__ = ['AbstractAttachment', 'Attachment']
class AbstractAttachment(models.Model):
    name = ...
    file = ...
    uploaded = ...
    def __str__(self) -> str:
        ...
    
    def save(self, *args, **kwargs): # -> None:
        ...
    
    class Meta:
        abstract = ...
    
    


class Attachment(AbstractAttachment):
    ...


