"""
This type stub file was generated by pyright.
"""

LANG_TO_LOCALE = ...
LANG_TO_LOCALE_ALTERNATIVES = ...
SUMMERNOTE_THEME_FILES = ...
def get_config():
    ...

def uploaded_filepath(instance, filename): # -> str:
    """
    Returns default filepath for uploaded files.
    """
    ...

def get_theme_files(theme, part): # -> tuple[str] | tuple[str, str] | tuple[str, str, str, str, str] | tuple[()]:
    """
    Return selected theme files
    """
    ...

def example_test_func(request): # -> Literal[True]:
    ...

def get_proper_language():
    """
    Return the proper language by get_language()
    """
    ...

def get_attachment_model(): # -> type[AbstractAttachment]:
    """
    Returns the Attachment model that is active in this project.
    """
    ...

def get_attachment_upload_to():
    """
    Return 'attachment_upload_to' from configuration
    """
    ...

def get_attachment_storage(): # -> Any | Storage:
    ...

def has_codemirror_config(): # -> bool:
    ...

