"""
This type stub file was generated by pyright.
"""

from django import forms

__all__ = ['SummernoteWidget', 'SummernoteInplaceWidget']
class SummernoteWidgetBase(forms.Textarea):
    def summernote_settings(self):
        ...
    
    def value_from_datadict(self, data, files, name): # -> Any | None:
        ...
    
    def use_required_attribute(self, initial): # -> Literal[False]:
        ...
    
    def render(self, name, value, attrs=..., **kwargs): # -> SafeString:
        ...
    
    def final_attr(self, attrs):
        ...
    


class SummernoteWidget(SummernoteWidgetBase):
    def render(self, name, value, attrs=..., **kwargs): # -> SafeString:
        ...
    


class SummernoteInplaceWidget(SummernoteWidgetBase):
    media = ...
    def render(self, name, value, attrs=..., **kwargs): # -> SafeString:
        ...
    
    def final_attr(self, attr):
        ...
    


